### PR TITLE
More typo fixing!

### PR DESCRIPTION
**Pull request by WouterSioen**

### CODE REVIEW

**Comment by WouterSioen** [comment]
hmm, looks like my other fixes are gone. I'll add them in another commit

**Comment by WouterSioen** [comment]
I just committed them without Pull requesting them, they are available in two other pull requests. (thanks for the great post btw)

**Comment by joejag** [comment]
Hi, I missed your PRs. Thank you very much for submitting them.

**Comment by joejag** [comment]
Closing as already exists

**Pull request closed without merging**
